# Generated by Django 4.0.3 on 2022-05-03 16:00

from django.db import migrations, models
import django.db.models.deletion
# import sqlalchemy.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backend_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(max_length=50)),
                ('app_admin_email', models.EmailField(max_length=50)),
                ('smtp_server', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=False, max_length=50, null=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=False, max_length=50, null=False)),
                ('hostname', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='network_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_status', models.IntegerField(default=0)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('event_desc', models.CharField(max_length=50)),
                ('event_host', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ONW.hosts')),
            ],
        ),
    ]
