# Generated by Django 4.0.3 on 2022-05-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ONW', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='network_events',
            name='app_id',
        ),
    ]
